---
deployment:
  tasks:
    - /usr/bin/git -C /home2/gaftimco/iscme.gaftim.com fetch origin
    - /usr/bin/git -C /home2/gaftimco/iscme.gaftim.com reset --hard origin/main
    - /usr/bin/php /home2/gaftimco/iscme.gaftim.com/artisan optimize:clear