---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/gaftimco/iscme.gaftim.com
    - /bin/cp -rf $PWD/public/build $DEPLOYPATH/public/build
    - /bin/cp -rf $PWD/routes $DEPLOYPATH/routes
    - /bin/cp -rf $PWD/app $DEPLOYPATH/app
    - /bin/cp -f $PWD/public/webhook.php $DEPLOYPATH/public/webhook.php
    - cd $DEPLOYPATH && php artisan optimize:clear 2>/dev/null || true