import React, { useMemo, useState } from 'react';
import { Head, router, usePage } from '@inertiajs/react';
import { Edit3, Mic2, Plus, Search, Star, Trash2 } from 'lucide-react';
import AdminLayout from '../../../Admin/AdminLayout';

export default function SpeakersIndex({ speakers }) {
    const [query, setQuery] = useState(''); const user = usePage().props.auth?.user;
    const rows = speakers.data || speakers;
    const filtered = useMemo(() => rows.filter(s => `${s.name} ${s.designation || ''} ${s.organisation || ''}`.toLowerCase().includes(query.toLowerCase())), [rows, query]);
    const remove = speaker => { if (confirm(`Delete “${speaker.name}”?`)) router.delete(`/admin/speakers/${speaker.id}`); };
    return <><Head title="Speakers" /><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-extrabold uppercase tracking-[.15em] text-blue-600">Conference content</p><h1 className="text-3xl font-black tracking-tight text-slate-900">Speakers</h1><p className="mt-2 text-sm text-slate-500">Manage keynote speakers, biographies and featured profiles.</p></div><a href="/admin/speakers/create" className="inline-flex items-center gap-2 rounded-xl bg-[#0d4c86] px-4 py-3 text-sm font-bold text-white no-underline shadow-lg shadow-blue-900/15 transition hover:-translate-y-0.5"><Plus size={17}/>Add speaker</a></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h2 className="font-extrabold text-slate-800">All speakers <span className="ml-1 text-sm font-medium text-slate-400">({speakers.total ?? rows.length})</span></h2></div><label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search speakers" className="w-64 rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-50"/></label></div><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="bg-slate-50 text-[10px] font-extrabold uppercase tracking-[.12em] text-slate-400"><tr><th className="px-5 py-3">Speaker</th><th className="px-5 py-3">Organisation</th><th className="px-5 py-3">Visibility</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(speaker => <tr key={speaker.id} className="hover:bg-blue-50/35"><td className="px-5 py-4"><div className="flex items-center gap-3">{speaker.photo ? <img src={`/storage/${speaker.photo}`} alt="" className="h-10 w-10 rounded-xl object-cover"/> : <span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><Mic2 size={18}/></span>}<div><strong className="block text-sm text-slate-800">{speaker.name}</strong><span className="text-xs text-slate-400">{speaker.designation || 'Speaker profile'}</span></div></div></td><td className="px-5 py-4 text-sm text-slate-600">{speaker.organisation || '—'}</td><td className="px-5 py-4"><div className="flex gap-1">{speaker.is_published ? <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">Published</span> : <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">Draft</span>}{speaker.is_featured && <span title="Featured" className="grid h-7 w-7 place-items-center rounded-full bg-amber-50 text-amber-600"><Star size={14} fill="currentColor"/></span>}</div></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><a href={`/admin/speakers/${speaker.id}/edit`} className="grid h-9 w-9 place-items-center rounded-lg text-blue-700 hover:bg-blue-50"><Edit3 size={17}/></a>{['super_admin','admin'].includes(user?.role) && <button onClick={() => remove(speaker)} className="grid h-9 w-9 place-items-center rounded-lg text-rose-600 hover:bg-rose-50"><Trash2 size={17}/></button>}</div></td></tr>)}{filtered.length === 0 && <tr><td colSpan="4" className="px-5 py-14 text-center text-sm text-slate-400">No speakers found.</td></tr>}</tbody></table></div></section></>;
}
SpeakersIndex.layout = page => <AdminLayout>{page}</AdminLayout>;
