import React from 'react';
import { Head, Link, router, usePage } from '@inertiajs/react';
import { Edit3, FileText, Plus, Trash2 } from 'lucide-react';
import AdminLayout from '../../../Admin/AdminLayout';

export default function PostsIndex({ posts }) {
 const user = usePage().props.auth?.user; const remove = post => { if(confirm(`Delete “${post.title}”?`)) router.delete(`/admin/posts/${post.id}`); };
 return <><Head title="News & Posts"/><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-extrabold uppercase tracking-[.15em] text-blue-600">Publishing</p><h1 className="text-3xl font-black tracking-tight text-slate-900">News & Posts</h1><p className="mt-2 text-sm text-slate-500">Write, schedule and publish conference announcements.</p></div><Link href="/admin/posts/create" className="inline-flex items-center gap-2 rounded-xl bg-[#0d4c86] px-4 py-3 text-sm font-bold text-white no-underline shadow-lg shadow-blue-900/15"><Plus size={17}/>New post</Link></div><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-left"><thead className="bg-slate-50 text-[10px] font-extrabold uppercase tracking-[.12em] text-slate-400"><tr><th className="px-5 py-3">Post</th><th className="px-5 py-3">Author</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Published</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{posts.data.map(post=><tr key={post.id} className="hover:bg-blue-50/35"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-50 text-indigo-700"><FileText size={17}/></span><div><strong className="text-sm text-slate-800">{post.title}</strong><span className="mt-1 block text-xs text-slate-400">{post.category?.name || 'Uncategorised'}</span></div></div></td><td className="px-5 py-4 text-sm text-slate-500">{post.author?.name || '—'}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${post.status === 'published' ? 'bg-emerald-50 text-emerald-700' : post.status === 'scheduled' ? 'bg-blue-50 text-blue-700' : 'bg-amber-50 text-amber-700'}`}>{post.status}</span></td><td className="px-5 py-4 text-sm text-slate-500">{post.published_at ? new Date(post.published_at).toLocaleDateString() : '—'}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Link href={`/admin/posts/${post.id}/edit`} className="grid h-9 w-9 place-items-center rounded-lg text-blue-700 hover:bg-blue-50"><Edit3 size={17}/></Link>{['super_admin','admin'].includes(user?.role) && <button onClick={()=>remove(post)} className="grid h-9 w-9 place-items-center rounded-lg text-rose-600 hover:bg-rose-50"><Trash2 size={17}/></button>}</div></td></tr>)}{!posts.data.length&&<tr><td colSpan="5" className="px-5 py-14 text-center text-sm text-slate-400">No posts created yet.</td></tr>}</tbody></table></section></>;
}
PostsIndex.layout=page=><AdminLayout>{page}</AdminLayout>;
