import React, { useRef, useState } from 'react';
import { Head, router } from '@inertiajs/react';
import { File, FileImage, FolderOpen, Image as ImageIcon, Plus, Trash2, UploadCloud, X } from 'lucide-react';
import AdminLayout from '../../../Admin/AdminLayout';

const isImage = item => item.mime_type?.startsWith('image/');
const formatSize = size => size > 1024 * 1024 ? `${(size / 1024 / 1024).toFixed(1)} MB` : `${Math.ceil(size / 1024)} KB`;

export default function MediaIndex({ media }) {
    const [uploading, setUploading] = useState(false); const [selected, setSelected] = useState(null); const input = useRef();
    const upload = files => { if (!files?.length) return; setUploading(true); router.post('/admin/media', { files: [...files] }, { forceFormData: true, onFinish: () => setUploading(false) }); };
    const remove = item => { if (confirm(`Delete “${item.original_name}”?`)) router.delete(`/admin/media/${item.id}`, { onSuccess: () => setSelected(null) }); };
    const items = media.data || [];
    return <><Head title="Media Library" /><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-extrabold uppercase tracking-[.15em] text-blue-600">Library</p><h1 className="text-3xl font-black tracking-tight text-slate-900">Media Library</h1><p className="mt-2 text-sm text-slate-500">Upload and organise images, documents and other website assets.</p></div><button onClick={() => input.current?.click()} className="inline-flex items-center gap-2 rounded-xl bg-[#0d4c86] px-4 py-3 text-sm font-bold text-white shadow-lg shadow-blue-900/15"><Plus size={17}/>{uploading ? 'Uploading…' : 'Upload files'}</button><input ref={input} onChange={e => upload(e.target.files)} type="file" multiple className="hidden" /></div>
    <div onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); upload(e.dataTransfer.files); }} className="mb-5 flex cursor-pointer items-center justify-center gap-3 rounded-2xl border-2 border-dashed border-blue-200 bg-blue-50/50 px-6 py-7 text-center transition hover:border-blue-400 hover:bg-blue-50" onClick={() => input.current?.click()}><UploadCloud className="text-blue-600"/><span className="text-sm font-bold text-blue-800">Drop files here or click to upload</span><span className="text-xs text-blue-600">Up to 20 files · 20 MB each</span></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="font-extrabold text-slate-800">All media <span className="ml-1 text-sm font-medium text-slate-400">({media.total ?? items.length})</span></h2><FolderOpen size={18} className="text-slate-400"/></div>{items.length ? <div className="grid grid-cols-2 gap-4 p-5 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-6">{items.map(item => <button onClick={() => setSelected(item)} key={item.id} className={`group overflow-hidden rounded-xl border text-left transition hover:-translate-y-0.5 hover:shadow-md ${selected?.id === item.id ? 'border-blue-500 ring-2 ring-blue-100' : 'border-slate-200'}`}>{isImage(item) ? <img src={`/storage/${item.path}`} alt={item.alt_text || ''} className="aspect-square w-full object-cover"/> : <span className="grid aspect-square place-items-center bg-slate-50 text-slate-400"><File size={34}/></span>}<span className="block truncate px-3 py-2 text-xs font-semibold text-slate-600">{item.original_name}</span></button>)}</div> : <div className="py-20 text-center text-slate-400"><ImageIcon className="mx-auto mb-3" size={34}/><p className="text-sm">No files uploaded yet.</p></div>}</section>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" onClick={() => setSelected(null)}><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl" onClick={e => e.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h3 className="font-extrabold text-slate-800">Media details</h3><button onClick={() => setSelected(null)} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100"><X size={20}/></button></div>{isImage(selected) ? <img src={`/storage/${selected.path}`} alt="" className="mb-4 max-h-64 w-full rounded-xl object-contain bg-slate-50"/> : <div className="mb-4 grid h-40 place-items-center rounded-xl bg-slate-50 text-slate-400"><File size={42}/></div>}<p className="truncate text-sm font-bold text-slate-700">{selected.original_name}</p><p className="mt-1 text-xs text-slate-400">{selected.mime_type} · {formatSize(selected.size)}</p><button onClick={() => remove(selected)} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-rose-50 px-3 py-2 text-sm font-bold text-rose-600 hover:bg-rose-100"><Trash2 size={15}/>Delete media</button></div></div>}</>;
}
MediaIndex.layout = page => <AdminLayout>{page}</AdminLayout>;
