import React from 'react';
import { Head, Link, usePage } from '@inertiajs/react';
import { CheckCircle2, FileText, PenLine, Sparkles } from 'lucide-react';
import AdminLayout from '../../Admin/AdminLayout';

const statStyle = [
    { label: 'Total pages', key: 'totalPages', icon: FileText, color: 'bg-blue-50 text-blue-700' },
    { label: 'Published', key: 'publishedPages', icon: CheckCircle2, color: 'bg-emerald-50 text-emerald-700' },
    { label: 'Drafts', key: 'draftPages', icon: PenLine, color: 'bg-amber-50 text-amber-700' },
];

export default function Dashboard(props) {
    const user = usePage().props.auth?.user;
    return <><Head title="Dashboard" /><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-extrabold uppercase tracking-[.15em] text-blue-600">Overview</p><h1 className="text-3xl font-black tracking-tight text-slate-900">Welcome back, {user?.name?.split(' ')[0]}.</h1><p className="mt-2 text-sm text-slate-500">Manage your conference website from one focused workspace.</p></div><a href="/admin/pages/create" className="inline-flex items-center gap-2 rounded-xl bg-[#0d4c86] px-4 py-3 text-sm font-bold text-white no-underline shadow-lg shadow-blue-900/15 transition hover:-translate-y-0.5 hover:bg-[#073c6c]"><PenLine size={16} />Create page</a></div>
    <section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{statStyle.map(({ label, key, icon: Icon, color }) => <article key={key} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.09em] text-slate-400">{label}</p><p className="mt-2 text-3xl font-black tracking-tight text-slate-800">{props[key]}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon size={19} /></span></div></article>)}<article className="rounded-2xl border border-blue-100 bg-gradient-to-br from-blue-600 to-[#0a3b68] p-5 text-white shadow-lg shadow-blue-900/15"><p className="text-xs font-bold uppercase tracking-[.09em] text-blue-100">Media library</p><p className="mt-2 text-2xl font-black">{props.mediaCount}</p><p className="mt-1 text-xs text-blue-100">Images, documents & assets</p></article></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-extrabold text-slate-800">Recently updated pages</h2><p className="mt-1 text-xs text-slate-500">Open the visual builder to continue editing.</p></div><Link href="/admin/pages" className="text-sm font-bold text-blue-700 no-underline">Manage pages</Link></div><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="bg-slate-50 text-[10px] font-extrabold uppercase tracking-[.12em] text-slate-400"><tr><th className="px-5 py-3">Page</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Updated</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{props.recentPages.map(page => <tr key={page.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><strong className="text-sm text-slate-800">{page.title}</strong><span className="mt-1 block text-xs text-slate-400">/{page.slug === 'home' ? '' : page.slug}</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${page.is_published ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{page.is_published ? 'Published' : 'Draft'}</span></td><td className="px-5 py-4 text-sm text-slate-500">{new Date(page.updated_at).toLocaleDateString()}</td><td className="px-5 py-4 text-right"><a href={`/admin/pages/${page.id}/builder`} className="inline-flex items-center gap-1 text-sm font-bold text-blue-700 no-underline"><Sparkles size={15} />Builder</a></td></tr>)}</tbody></table></div></section></>;
}
Dashboard.layout = page => <AdminLayout>{page}</AdminLayout>;
